import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/components/provider'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<Provider>
				<body className={clsx(inter.className, 'flex h-full w-full bg-fixed items-center align-middle')} style={{
					backgroundImage: 'url("/BackGroundWater.jpg")',
				}}>
					{children}
				</body>
			</Provider>
		</html>
	)
}
