import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Provider from '@/components/provider'
import background from '@/public/BackGroundWater.jpg'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<Provider>
				<body className={clsx(inter.className, 'bg-fixed')} style={{
								backgroundImage: 'url("/BackGroundWater.jpg")',
							}}>

					{/* <div className="h-screen">
						<div className="absolute -z-10 h-full w-full">
							<Image
								src="/BackGroundWater.jpg"
								alt="Background Image"
								layout="fill"
								objectFit="cover"
								priority
								quality={100}
							/>
						</div>
						{children}
					</div> */}

					{/* <div className="absolute z-0 w-full h-full bg-transparent">
						<div
							className="absolute w-full h-full bg-cover bg-fixed"
							style={{
								backgroundImage: 'url("/BackGroundWater.jpg")',
							}}
						></div>
					</div> */}
					{children}

				</body>
			</Provider>
		</html>
	)
}
